### ISSUE TITLE
option to group entries

### ISSUE THREAD

**Issue by nickbe** [BenjaminHae/Password-Manager#32]
I've now more than 150 entries in my database.

An additional **group** field would be nice and showing the entries grouped by that field.
This **group** field can be a simple textfield (no predefined values necessary here)

**Comment by BenjaminHae** [comment]
Doesn't the tag functionality fulfill most of this?
You can't exactly group, but you can hide everything else.

**Comment by nickbe** [comment]
I know. But grouping would mean having group headers in the list.

**Comment by BenjaminHae** [comment]
Maybe grouping by the first tag?

**Comment by nickbe** [comment]
Good idea. Easy enough to handle when entering tags. Excellent idea :)

**Comment by BenjaminHae** [comment]
ok, now I'm a little bit more confident that it works. Trying it out should be safe.

**Comment by nickbe** [comment]
Let me try that tomorrow :) I'm done for today X-)
